// <auto-generated />
using System;
using Kitchen.Infrastructure.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kitchen.Infrastructure.DAL.Migrations
{
    [DbContext(typeof(KitchenDbContext))]
    [Migration("20260513095704_Rename_IngredientToStockItem_And_IngredientTypeToProductDefinition")]
    partial class Rename_IngredientToStockItem_And_IngredientTypeToProductDefinition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kitchen.Core.Domain.Entities.ProductDefinition", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.HasKey("Name");

                    b.ToTable("ProductDefinitions");
                });

            modelBuilder.Entity("Kitchen.Core.Domain.Entities.StockItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<int>("Location")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TypeName");

                    b.ToTable("StockItems");
                });

            modelBuilder.Entity("Kitchen.Core.Domain.Entities.StockItem", b =>
                {
                    b.HasOne("Kitchen.Core.Domain.Entities.ProductDefinition", "Type")
                        .WithMany()
                        .HasForeignKey("TypeName");

                    b.Navigation("Type");
                });
#pragma warning restore 612, 618
        }
    }
}
